### PR TITLE
Close the zkclient when EmbeddedKafka is stopped

### PR DESCRIPTION
**Pull request by Jarlakxen**

### CODE REVIEW

**Comment by bfil** [comment]
Thanks for the pull request.

I remember trying to add those exact lines as well, but I had some issues with them, `zkClient.close` sometimes ended up blocking the execution forever, have you experienced anything like it?

**Comment by Jarlakxen** [comment]
I was not aware of that issue, I'm using zkClient 0.5. My issue is that if you don't close the client this keep trying to reconnect forever. This makes the execution of the tests never ends.
Mm... knowing this situation, what do you think that could be the best approach?

**Comment by bfil** [comment]
I will try again to put those lines back in and see if I can reproduce the issues I had.

I remember race conditions around the test executions as well, with the tests never ending like you described. But I though I sorted those ones.

I'll try it out and let you know how it goes!

**Comment by bfil** [comment]
I've published a new snapshot (`0.2.0-SNAPSHOT`) with the change, can you try it out and let me know if it fixes your issue?

**Comment by Jarlakxen** [comment]
It works great! =)

**Comment by bfil** [comment]
Good to hear that, I've released a new fixed version (`0.2.0`), which also sorted some issues around topics deletion, that should work properly now.

I'll close this, thanks for your input!

**Pull request closed without merging**
